version: 0.1.0-beta{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_commits:
  files:
    - util/**/*
    - docs/**/*
    - README.md
    - LICENSE
    - TODO.txt
    - '*.png'


image: Visual Studio 2017
configuration: Release
#environment:
#  COVERALLS_REPO_TOKEN:
#    secure: sbStw71imn5c9ATjfPvDotgSyReJHM+il7wz8/083Xy3BONRyRxIg0cOjGAr8evI
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    dotnet restore
    nuget restore
    dotnet build -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE"
    pushd SystemNet.Abstractions
    dotnet pack -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE" --include-symbols
    popd

test: on
artifacts:
- path: '**\bin\release\*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
  on:
    branch: master